name: Open Docs PR

on:
  push:
    branches: [master]

jobs:      
  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        env:
          DOCKER_BUILDKIT: 1
        run: rm -rf docs-output && docker build -o docs-output -f ./.github/actions/docsgen/Dockerfile.docsgen .

      - name: Checkout latest docs
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOCS_GITHUB_TOKEN }}
          repository: blockstack/docs.blockstack
          path: docs.blockstack

      - name: Branch and commit
        id: push
        run: |
          cd docs.blockstack
          git config user.email "robots@robots.actions"
          git config user.name "PR Robot"
          if $(git show-ref --verify --quiet refs/heads/auto/clarity-ref-update); then
            git branch -D auto/clarity-ref-update
          fi
          git checkout -b auto/clarity-ref-update
          cp ../docs-output/clarityRef.json ./_data/clarityRef.json
          if $(git diff --quiet --exit-code); then
            echo "No clarityRef.json changes, stopping"
            echo "::set-output name=open_pr::0"
          else
            git remote add kantai https://github.com/kantai/docs.blockstack
            git add _data/clarityRef.json
            git commit -m "auto: update clarityRef.json from stacks-blockchain@${GITHUB_SHA}"
            git push --force kantai auto/clarity-ref-update
            echo "::set-output name=open_pr::1"
          fi
      - name: Open PR
        if: ${{ steps.push.outputs.open_pr == '1' }}
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.DOCS_GITHUB_TOKEN }}
          script: |
            // check if a pull exists
            const existingPulls = await github.pulls.list({
              owner: "kantai",
              repo: "docs.blockstack",
              head: "kantai:auto/clarity-ref-update"});
            console.log(existingPulls.data);
            if (existingPulls.data.length == 0) {
               // Open PR if one doesn't exist
               console.log("2");
               let result = await github.pulls.create({
                 owner: "kantai",
                 repo: "docs.blockstack",
                 title: "Auto: Update API documentation from stacks-blockchain",
                 head: "kantai:auto/clarity-ref-update",
                 base: "master",
                 body: "Update API documentation from the latest in `stacks-blockchain`",
               });
               console.log(result);
            }
